server:
  port: 9110
spring:
  application:
    name: stock-tcc-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: db
    active: db
  output:
    ansi:
      enabled: detect
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  edas:
    migration:
      subscribes: nacos # ,eureka

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/
