server:
  port: 9110
spring:
  application:
    name: stock-tcc-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: db
    active: db
  output:
    ansi:
      enabled: detect


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
