server:
  port: 9109
spring:
  application:
    name: order-tcc-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: db
    active: db
  output:
    ansi:
      enabled: detect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/