server:
  port: 9109
spring:
  application:
    name: order-tcc-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: db
    active: db
  output:
    ansi:
      enabled: detect

hmily:
  server:
    configMode: zookeeper
    appName: order-service
remote:
  zookeeper:
    serverList: 127.0.0.1:2181 #你的zookeeper服务地址，多个使用逗号分隔
    fileExtension: yml #zookeeper上配置文件的格式（properties或者yml）二选一
    path: /hmily/tcc #zookeeper上配置文件的路径
    update :   #默认是false ，是否需要将本地的配置文件写到zookeeper
    updateFileName:  #update属性为true时候 ，配置文件名称，位于项目的 resource文件夹下的yaml格式

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/